### ISSUE TITLE
Issue while building

### ISSUE THREAD

**Issue by LeRatierBretonnien** [PDOK/mapproxy-docker#19]
Error during the build process : 
```
 => ERROR [ 3/13] RUN pip3 install flup Numpy PyYAML boto3 Pillow requests Shapely eventlet gunicorn uwsgi prometheus_client lxml azure-storage-blob pyproj==2.2.0                      27.5s 
```

```
27.38 Traceback (most recent call last):
27.38   File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 143, in main
27.38     status = self.run(options, args)
27.38   File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 338, in run
27.38     resolver.resolve(requirement_set)
27.38   File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 102, in resolve
27.38     self._resolve_one(requirement_set, req)
27.38   File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 256, in _resolve_one
27.38     abstract_dist = self._get_abstract_dist_for(req_to_install)
27.38   File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
27.38     self.require_hashes
27.38   File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 298, in prepare_linked_requirement
27.38     abstract_dist.prep_for_dist(finder, self.build_isolation)
27.38   File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 100, in prep_for_dist
27.38     self.req.load_pyproject_toml()
27.38   File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 428, in load_pyproject_toml
27.38     str(self)
27.38   File "/usr/lib/python3/dist-packages/pip/_internal/pyproject.py", line 43, in load_pyproject_toml
27.38     pp_toml = pytoml.load(f)
27.38   File "/usr/share/python-wheels/pytoml-0.1.2-py2.py3-none-any.whl/pytoml/parser.py", line 303, in load
27.38     filename=fin.name)
27.38   File "/usr/share/python-wheels/pytoml-0.1.2-py2.py3-none-any.whl/pytoml/parser.py", line 370, in loads
27.38     toks.expect('=', 'expected_equals')
27.38   File "/usr/share/python-wheels/pytoml-0.1.2-py2.py3-none-any.whl/pytoml/parser.py", line 250, in expect
27.38     self.error(error_text)
27.38   File "/usr/share/python-wheels/pytoml-0.1.2-py2.py3-none-any.whl/pytoml/parser.py", line 253, in error
27.38     raise TomlError(message, self.pos[0][0], self.pos[0][1], self._filename)
27.38 pytoml.core.TomlError: /tmp/pip-install-9l7lr070/lxml/pyproject.toml(48, 8): expected_equals
```

**Comment by kad-dirc** [comment]
Thanks @LeRatierBretonnien , I have pinned the `lxml` dependecy on the highest version that worked.
